### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by WashWashSheep** [Barsik008/PossumBot#10]
requireStack: [ 'C:\\Users\\Litet\\Desktop\\PossumBot-master\\bot.js' ] error is popping up

**Comment by Barsik008** [comment]
did you install nodejs?

**Comment by WashWashSheep** [comment]
I used that file only..but I did have a preinstalled node.js from a separate bot that I was designing

**Comment by Barsik008** [comment]
did you run npm install?

**Comment by WashWashSheep** [comment]
From the first bot yeah but I'll add it for this one rn

**Comment by Barsik008** [comment]
okay just follow the steps in the readme and it should work.

**Comment by BeastGamerYT** [comment]
Can you make something which can give me the ownership of that server

**Comment by Barsik008** [comment]
@BeastGamerYT yes ofc.
