### ISSUE TITLE
Commands not working.

### ISSUE THREAD

**Issue by xeRRR** [Barsik008/PossumBot#108]
![image](https://user-images.githubusercontent.com/79174548/114381546-e9cdab80-9b93-11eb-9b0c-e8d521d43d3d.png)
this.
Bot invited, prefix is "!", followed all the steps, however it ain't working.

**Comment by Barsik008** [comment]
@xeRRR is there anything in the console?

**Comment by xeRRR** [comment]
No. Everything seems to work just fine.

**Comment by xeRRR** [comment]
However, both bots seem to be offline.

**Comment by Barsik008** [comment]
@xeRRR Make sure that the bot is running.

**Comment by xeRRR** [comment]
And how can I do that?

**Comment by Barsik008** [comment]
@xeRRR `node bot.js` in the console

**Comment by xeRRR** [comment]
Yeah, it works. Thanks.
