### ISSUE TITLE
WScript doesnt work

### ISSUE THREAD

**Issue by JoeHair44** [Barsik008/PossumBot#109]
The bot has been set up successfully, and it starts. Node.js was installed and the token matches, but none of the commands work. I believe the WScript.sleep 3000 is the issue because one thing I notice is that when I start the bot, it isn't recognized as a command. Is there a fix for this?
![Screenshot (17)](https://user-images.githubusercontent.com/62626925/115973512-8cd2dd80-a523-11eb-95a0-2db0932414d2.png)

**Comment by Barsik008** [comment]
@JoeHair44 launch the bot through the console with `node bot.js`
