### ISSUE TITLE
ACTIVATING THE BOT

### ISSUE THREAD

**Issue by Flippy101mph** [Barsik008/PossumBot#125]
ok so I followed ever step up until activating the bot itself I the batch file isn't running properly and I think I'm missing something
and I'm not even sure if this really will work or not so if anyone can help me take over chat zone that'd be great

**Comment by Barsik008** [comment]
@Flippy101mph start the bot through the console

**Comment by REAPERSDmise** [comment]
where is the bot???

**Comment by REAPERSDmise** [comment]
i cant download bot

**Comment by Flippy101mph** [comment]
I managed to get it working but then I got kicked from the server
