### ISSUE TITLE
I want possum bot filr

### ISSUE THREAD

**Issue by Aryankansotia** [Barsik008/PossumBot#126]
Hi,
I am aryan
I want possum bot file
Or possum bot invite link
Because i have issue to get possum bot
I am unable to get possum bot
I want possum bot file

**Comment by Aryankansotia** [comment]
Bro I used that file but it's not working so I only want possum bot client
id

**Comment by Barsik008** [comment]
@Aryankansotia what exactly isn't working?

**Comment by Aryankansotia** [comment]
Bro I told you I am unable to run the bot in my linux I tryed too many times

Please give me the bot token I will invite it

If you not want to give the bot token

So this is my

Email - ***@***.***

Password - @9649267610

Log my account in your device and make it run it but I only want bot token

**Comment by Barsik008** [comment]
@Aryankansotia I can help you with setting up the bot, but i can't give you the bot invite link, sorry

**Comment by Aryankansotia** [comment]
Hello Dear Barsik008

I am Aryan and I tried to run the bot in termux terminal many time with
start.bat,start.sh and node bot.js commands but the bot didn't activated it
shows the same error (see screenshots)

There is any solution of this error

Please will you Run it with my information

My information

Gmail - ***@***.***

Password - @9649267610

Bot name - Cobra

Bot token - ODg2OTc1Njk1OTE2NTMxNzIy.YT9afQ.233r6QYpF1FNR48go2BgpqQM3W0

Client Id - 886975695916531722

**Comment by Aryankansotia** [comment]
I told you many time and I am telling you again

Hello Dear Barsik008

I am Aryan and I tried to run the bot in termux terminal many time with
start.bat,start.sh and node bot.js commands but the bot didn't activated it
shows the same error (see screenshots)

There is any solution of this error

Please you can Run it with my account

My information

Gmail - ***@***.***

Password - @9649267610

Bot name - Cobra

Bot token - ODg2OTc1Njk1OTE2NTMxNzIy.YT9afQ.233r6QYpF1FNR48go2BgpqQM3W0

Client Id - 886975695916531722

**Comment by Aryankansotia** [comment]
First tell me what you want

**Comment by Aryankansotia** [comment]
Sorry for saying this
Don't be dumb
Why you are not understanding
Why you are saying only one sentence - what exactly isn't working

I said many time the full bot isn't working

I gave my full information so you can activate the bot

Note - don't reply the sentence - what exactly isn't working

**Comment by Barsik008** [comment]
@Aryankansotia Can you describe what exactly isn't working?

**Comment by Aryankansotia** [comment]
Can you describe what you want to know

**Comment by Barsik008** [comment]
@Aryankansotia What exactly isn't working?

**Comment by Aryankansotia** [comment]
I think you are a bot because you are only replying on sentence (what
exactly isn't working)

I said many times the whole bot isn't working

The start.bat and start.sh command not working

If you are human don't reply again what isn't working

**Comment by Barsik008** [comment]
@Aryankansotia Start the bot through the console and it should work

**Comment by Aryankansotia** [comment]
Which console

**Comment by Barsik008** [comment]
@Aryankansotia terminal

**Comment by Aryankansotia** [comment]
Yes see screenshot

Its termux terminal emulator

See the error

**Comment by Barsik008** [comment]
@Aryankansotia start it through termux then

**Comment by Aryankansotia** [comment]
Bro I said it I tried to start it through termux but it shows the same error

**Comment by Barsik008** [comment]
@Aryankansotia send me the error "bro"

**Comment by Aryankansotia** [comment]
Bro I attached the screenshot before and I am sending it again

See and tell me why the error occurred

**Comment by Barsik008** [comment]
@Aryankansotia send me the error message instead of the screenshot

**Comment by Aryankansotia** [comment]
Bro I said the error is in screenshot

**Comment by Barsik008** [comment]
@Aryankansotia Which screenshot?

**Comment by Aryankansotia** [comment]
This

that I attached in this mail

**Comment by Barsik008** [comment]
@Aryankansotia I don't see it

**Comment by Aryankansotia** [comment]
I sent but it's not showing you

Did you have a discord account

**Comment by Aryankansotia** [comment]
If you have a discord account tell me you username I will direct message you

**Comment by Barsik008** [comment]
@Aryankansotia what's this scary thing called a "discord" ?

**Comment by Aryankansotia** [comment]
Did you listened about attaching a file with a mail in your whole life
because you don't know about attaching a screenshot with a mail

If you have any other way to talk and send a file exept gmail bit worldwide
because I am in India so we can't chat with whatsapp or telegram

tell me

**Comment by Aryankansotia** [comment]
Ok
I will try

**Comment by Barsik008** [comment]
@Aryankansotia ok
