### ISSUE TITLE
commands not working

### ISSUE THREAD

**Issue by N2KJoshua** [Barsik008/PossumBot#13]
title explains it, i got it onto my friends server but the commands arent working.

**Comment by N2KJoshua** [comment]
i THINK its because mee6 uses same prefix, not sure though. any way to change the prefix once i have hte bot already active?

**Comment by Barsik008** [comment]
Check if the bot has admin perms, whats the error in the console?
And i believe you can change the prefix in botsettings.json

**Comment by N2KJoshua** [comment]
turns out it was just the bot auto-turning off after a bit. nice bot
