### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by kingdom51** [Barsik008/PossumBot#131]
this is probably really self explanatory and I'm just too blind to see it but where do I input the commands given? do I enter them on my actual account or do I have to find a way to access the bot and enter it from there?

**Comment by Barsik008** [comment]
@kingdom51 You can use any accounts that's on the same server as the bot

**Comment by kingdom51** [comment]
![image](https://user-images.githubusercontent.com/95322035/144918333-9d2de2b3-d4f5-4236-8938-32a6c4201760.png)

**Comment by Barsik008** [comment]
@kingdom51 is the bot enabled in the console?

**Comment by kingdom51** [comment]
i had to rerun start.bat thanks
