### ISSUE TITLE
bot??

### ISSUE THREAD

**Issue by REAPERSDmise** [Barsik008/PossumBot#140]
I cant find the bot how do i download it?

**Comment by Barslk008** [comment]
using terminal if your on chrome OS you can find videos on how to download the linux development and apps but if your on windows use the command prompt or crosh or something idk

**Comment by REAPERSDmise** [comment]
> using terminal if your on chrome OS you can find videos on how to download the linux development and apps but if your on windows use the command prompt or crosh or something idk

doesnt help im bad at this

**Comment by Barsik008** [comment]
@Barslk008 woah, my clone?
