### ISSUE TITLE
cant invite to server

### ISSUE THREAD

**Issue by Majestichero** [Barsik008/PossumBot#16]
do I already need to have permissions to the server to invite it or is there something im missing

**Comment by Banana-Here** [comment]
Did you get the bot to work? If so, could you send me a video tutorial of it? Once i get one, i can whip the bot up easily. Thanks, if you read this!

**Comment by Creator-Jesse** [comment]
you just need to extract the zip to a folder and then open cmd type cd "your directory(folder)" and then say npm install then it should just say the rest in the github description...

**Comment by Barsik008** [comment]
@Majestichero You need to convince an admin to invite the bot for you.
