### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by mugglemax** [Barsik008/PossumBot#19]
I've activated it, and the server owner added the bot to the server. But none of the commands are working. is there a prefix? Or do you just type !myakish ? because it's not working and i dont get it. Is the bot supposed to be online? How do you get it to come online? Helpp please

**Comment by Barsik008** [comment]
@mugglemax To get the bot to go online type `cd /path/to/bot and node` `bot.js` in your terminal.
If the bot doesn't work while its online please send me the terminal output

**Comment by mugglemax** [comment]
Here's the output: 

> PossumBot Is Now Activated
> https://discordapp.com/oauth2/authorize?client_id=683908757213675608&permissions=8&scope=bot

I used that url to add to the server. Bot still doesnt come online and commands don't work.

**Comment by Barsik008** [comment]
@mugglemax Did you close the console after inviting the bot?

**Comment by mugglemax** [comment]
no- am i supposed to?

**Comment by Barsik008** [comment]
@mugglemax Are there any errors in the console?

**Comment by jeo4123** [comment]
only the @everyone and leave server perms work

**Comment by jeo4123** [comment]
the myakish
arturdebil
dont work for me idk why tho

**Comment by Barsik008** [comment]
@jeo4123 any errors in the console?

**Comment by jeo4123** [comment]
i dont know lol im not exactly great at coding but the whole thing runs and i was testing it out when the bot had full perms

**Comment by Barsik008** [comment]
@jeo4123 so does it work with full perm or not?

**Comment by jeo4123** [comment]
nah it doesn't

**Comment by Barsik008** [comment]
@jeo4123 what does the console say?
