### ISSUE TITLE
app.js code

### ISSUE THREAD

**Issue by YusufSlither** [Barsik008/PossumBot#20]
everything is working except I got an error on app.js idk what code i need in app.js for it to work, if anyone can help please do

**Comment by Barsik008** [comment]
please send me the error.

**Comment by linusssSss** [comment]
If I try to activate the bot it gives me this: 

[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\Users\Linus\Desktop\Rebellion\Botz\PossumBot-master\PossumBot-master\bot.js:2:17)
[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Linus\\Desktop\\Rebellion\\Botz\\PossumBot-master\\PossumBot-master\\bot.js'[39m
  ]
}
