### ISSUE TITLE
"code: [32m'MODULE_NOT_FOUND' [39m," when running node bot.js

### ISSUE THREAD

**Issue by torriancloud** [Barsik008/PossumBot#26]
![image](https://user-images.githubusercontent.com/60531719/81124696-f4df7c80-8eea-11ea-80dd-8f87fead2c72.png)

All the files in the repo are intact.

**Comment by Barsik008** [comment]
you are supposed to cd into the repo first....

**Comment by k2wavey** [comment]
and how do we do that?

**Comment by AGR2006** [comment]
> you are supposed to cd into the repo first....

wdym?

**Comment by AGR2006** [comment]
I cdED into the repo, still same error

**Comment by Tezrk** [comment]
> you are supposed to cd into the repo first....

how do we do this exactly?

**Comment by AGR2006** [comment]
@Tezrk use cd downloads then go further till you find the file then do npm install

**Comment by ZenoMilk12** [comment]
Try to install the module manualy.
When o tried to install some program in Python it gave me that the module not found, then I tried in another window pip3 inatall NameOfModule and it worked.I know this is JavaScript not Python but it should be the same.

**Comment by UnlockDep** [comment]
do
npm i discord.js
