### ISSUE TITLE
NPM Install

### ISSUE THREAD

**Issue by Littlecris** [Barsik008/PossumBot#33]
I have this very persistent issue, whenever I chance directories to the file, then I run npm install, it goes fine for a bit, then at extract it just stops, and if you click anything terminal crashes, Running on Windows, I tried the latest version and 10.13.0, but it's the same issue over and over.

**Comment by Barsik008** [comment]
are you in the right directory?

**Comment by Littlecris** [comment]
I fixed it, it was in the right directory, prob is it hangs on extract, seemed to be a npm install prob, so when I went to directory, npm install -d, worked! I never came across this problem so far with my experiences with node, but it works now.
