### ISSUE TITLE
node bot.js

### ISSUE THREAD

**Issue by reaganking97** [Barsik008/PossumBot#37]
PS C:\Users\Paula\Downloads\PossumBot> node bot.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\Paula\Downloads\PossumBot\bot.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []

**Comment by reaganking97** [comment]
![image](https://user-images.githubusercontent.com/69058435/89077778-a0606780-d348-11ea-90f0-dc28d657f511.png)

**Comment by reaganking97** [comment]
i figured it out

**Comment by B3B0-glitch** [comment]
hey howd you figure this out i havr the same problem right now

**Comment by Barsik008** [comment]
@B3B0-glitch you have to cd into the folder
