### ISSUE TITLE
issue on step 9

### ISSUE THREAD

**Issue by somerandoonline** [Barsik008/PossumBot#41]
Error: Cannot find module 'C:\Users\Computer\bot.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

I open the botsettings.json as a notepad file and then saved that back to the original .zip folder. idk what im doing wrong

**Comment by Barsik008** [comment]
@somerandoonline  you have to unzip the folder first.

**Comment by Barsik008** [comment]
@somerandoonline and you have to cd into the foldeer.

**Comment by yoshisaac** [comment]
@somerandoonline  and @Barsik008  I unzipped and cd into it and I get that error.

**Comment by Barsik008** [comment]
@yoshisaac You need to type "npm install" first.
