### ISSUE TITLE
Ошибка блять

### ISSUE THREAD

**Issue by BevirAway** [Barsik008/PossumBot#46]
TypeError: Cannot read property 'addRole' of null
    at Object.module.exports.run (D:\PossumBot-master\commands\myakish.js:15:24)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
Помоги пожалуйста
Артурдебил

**Comment by Barsik008** [comment]
@BevirAway У бота админка есть, блять?

**Comment by BevirAway** [comment]
> @BevirAway У бота админка есть, блять?

Да блять, я тебе блять на реддите блять написал блять, добавь меня блять пожалуйста в дискорд again#0997

**Comment by Barsik008** [comment]
@BevirAway Блять, я тебя добавил, блять в дискорде.

**Comment by rizzini** [comment]
same here

**Comment by rizzini** [comment]
I added you, again#0997.
