### ISSUE TITLE
NPM install issues

### ISSUE THREAD

**Issue by wofa41** [Barsik008/PossumBot#49]
C:\Program Files\Possum Bot>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Program Files\Possum Bot\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Program Files\Possum Bot\package.json'
npm WARN Possum Bot No description
npm WARN Possum Bot No repository field.
npm WARN Possum Bot No README data
npm WARN Possum Bot No license field.

Has this installed properly?

**Comment by Barsik008** [comment]
No. Looks like the bot folder is corrupted.

**Comment by Christ-an** [comment]
The same is at me too. But it looks like the ZIP folder that u can download from here (Github) is the original data broken could u fix it barsik ;((( pls

Lg Chris

**Comment by Christ-an** [comment]
Or it is smt here but I download the file unzip it and want to download it but it just dont work. this issue.

**Comment by Barsik008** [comment]
@Christ-an @wofa41 i've just tested it myself and it works, could you tell me the steps to reproduce this?

**Comment by Christ-an** [comment]
i already had node.js so i just clicked to download the zip. and when i followed the steps point for point came this error..

**Comment by Barsik008** [comment]
@Christ-an what version of node do you have?

**Comment by Christ-an** [comment]
I have v12.14.1.

**Comment by Christ-an** [comment]
I now installed the latest version and its still not working

You have discord?

**Comment by Barsik008** [comment]
@Christ-an does the folder that you downloaded have the `package.json` file?

**Comment by Christ-an** [comment]
Yes it has the file in it.

**Comment by Barsik008** [comment]
@Christ-an can u send me a video of you doing all the steps?

**Comment by Christ-an** [comment]
Yes I did. The unziped folder oh wait

**Comment by Christ-an** [comment]
yes it worked i went in cd possumbot-master and again cd possumbot-master i first did only once
