### ISSUE TITLE
Only command that works is !leaveserver

### ISSUE THREAD

**Issue by baby-Mario** [Barsik008/PossumBot#56]
Only command that works is !leaveserver

**Comment by Christ-an** [comment]
on me too

**Comment by Christ-an** [comment]
None of the commands are working at the server idk why

**Comment by Barsik008** [comment]
@Christ-an @baby-Mario does the bot have admin perms?

**Comment by baby-Mario** [comment]
Yes i put it in a server that I myself own and gave him admin perms

**Comment by baby-Mario** [comment]
Okay I tried it again now the ban command is the only one that doesn't work.

**Comment by Christ-an** [comment]
I think I tried the ban command too and it worked kinda he kicked the person but not banned him its kinda the same.

**Comment by Christ-an** [comment]
So the commands are working

**Comment by Barsik008** [comment]
Alright, im trying to fix the ban all command atm.

**Comment by baby-Mario** [comment]
preeshiate
