### ISSUE TITLE
none of the commands would work except of !leaveserver and !servernotgood

### ISSUE THREAD

**Issue by martinartin222** [Barsik008/PossumBot#60]
what le topic say

**Comment by Barsik008** [comment]
@martinartin222 Are there any errors in the console? Also does the bot have admin perms?

**Comment by martinartin222** [comment]
> @martinartin222 Are there any errors in the console? Also does the bot have admin perms?

it has both admin and no errors

**Comment by IronHorseTV** [comment]
yeah 
it says insufficient permissions

**Comment by Barsik008** [comment]
@martinartin222 @IronHorseTV the bot won't work unless it had admin perms.
