### ISSUE TITLE
Can I give myself more perms besides Administrator?

### ISSUE THREAD

**Issue by Umeor** [Barsik008/PossumBot#68]
The 'Dope Role' only allows one perm, is there a way to change this and add more? If so, how? I'm trying to do a command with a bot, but it says I don't have the required roles.

**Comment by Barsik008** [comment]
@Umeor you can change the permissions in `commands/myakish.js`

**Comment by Umeor** [comment]
Nice! Is this an easy fix or will it require some effort? For reference, I have 0 coding knowledge whatsoever.

**Comment by Barsik008** [comment]
@Umeor It's pretty easy, but changing it won't do anything since the admin perm automatically gives the role all permissions

**Comment by Umeor** [comment]
Ah, well I'll try anyway and get back to you. Thanks so much! The bot is great btw:)

**Comment by Umeor** [comment]
Okay, you were right. The command is owner-only and I don't think there's a way I can bypass that. However, could the Dope Role be put above existing roles? I know it defaults to the bottom, and servers with color roles won't allow you to ban someone with a color role unless your admin role is above theirs.

**Comment by Umeor** [comment]
@Barsik008 And one more thing, is there a command to remove the admin role?

**Comment by Barsik008** [comment]
@Umeor if another role with admin perms is higher than `dope role` you can't do anything about it.

**Comment by Umeor** [comment]
@Barsik008 Is there gonna be an update to change that?

**Comment by Barsik008** [comment]
@Umeor probably not.
