### ISSUE TITLE
arturdebil isnt working

### ISSUE THREAD

**Issue by ymzmo** [Barsik008/PossumBot#7]
hi i tried the arturdebil command and it didnt work and is there a way it can kick all the bots aswell

**Comment by Barsik008** [comment]
When you add the bot the administrator box needs to be ticked. To ban all the bots possum bot needs to have a higher role than them.

**Comment by ymzmo** [comment]
it did get admin lol

**Comment by Barsik008** [comment]
@ymzmo Then it should work lol
