### ISSUE TITLE
Bot says its offline

### ISSUE THREAD

**Issue by CommunistHentai** [Barsik008/PossumBot#70]
When I added the bot to a server that I own to test test it out, it says that it's offline. Will it turn online eventually or did I do something wrong while downloading? Please help.

**Comment by Mariic33** [comment]
You always have to start the bot manually when you want to use it. You can do this by opening "node.js command prompt", typing "cd and then the path where the Possumbot folder is saved and then you have to type node bot.js
Now it should work properly.

**Comment by Barsik008** [comment]
you can also run `start.bat` to start the bot.

**Comment by CommunistHentai** [comment]
Thank you! Now to use it for educational purposes.
