### ISSUE TITLE
The command in the PR was supposed to ghost ping

### ISSUE THREAD

**Issue by NightYoshi370** [Barsik008/PossumBot#77]
What do you mean by "not working correctly"? Just because you didn't see it as intended doesn't mean that it's broken.

What do you mean by "You deserve what's coming to you"??? What did I do?

**Comment by Barsik008** [comment]
@NightYoshi370 calm down

**Comment by NightYoshi370** [comment]
I mean, I'm getting emails and Twitter DMs because of it.
![image](https://user-images.githubusercontent.com/18664762/103505392-fad98480-4e0e-11eb-97fc-820d6bf407e6.png)
![image](https://user-images.githubusercontent.com/18664762/103505430-0dec5480-4e0f-11eb-8daf-0592bb80cf39.png)

**Comment by Barsik008** [comment]
@NightYoshi370 What does this have to do with me?

**Comment by NightYoshi370** [comment]
I thought you were trying to coup something since I saw this in the message: "PS(NightYoshi370 you deserve whats coming to you)"

**Comment by Barsik008** [comment]
@NightYoshi370 Yeah, I hire people to annoy you.

**Comment by yeetyeet96** [comment]
@Barsik008 lmfaooo

**Comment by NightYoshi370** [comment]
Ok, looking back, I overreacted, sorry.
Could we perhaps discuss this though?

**Comment by Barsik008** [comment]
ok
