### ISSUE TITLE
hey. with the ban command i have been testing with two of my friends. the first time i ran it it banned one of them. the next time it banned the other. how do i ensure it bans both?

### ISSUE THREAD

**Issue by cribled** [Barsik008/PossumBot#83]
basically its only banning 1 of them and when i try to run the ban command again right after it doesnt work until i run the startup command in the cmd again even if the bot is still online.

**Comment by Barsik008** [comment]
@cribled are intents enabled?

**Comment by cribled** [comment]
> @cribled are intents enabled?

Yes I believe intents are enabled.

**Comment by cribled** [comment]
presence and server members intent is enabled yes.

**Comment by notSalt** [comment]
Might also want to list details such as bot permissions.
Are you sure the bot had the permissions to ban both members? It will filter out members that cannot be banned so that could be the case.

**Comment by pogchamp12r** [comment]
> @cribled are intents enabled?

can u fuck up this server for me PLEASE bc these guys are dicks and they got loads of pedos in there server and i want them to know pain if u could

**Comment by pogchamp12r** [comment]
> @Barsik008 can u fuck up this server for me PLEASE bc these guys are dicks and they got loads of pedos in there server and i want them to know pain if u could

**Comment by Barsik008** [comment]
@pogchamp12r are they racist?
