### ISSUE TITLE
Ban command not working

### ISSUE THREAD

**Issue by Swampyemerson** [Barsik008/PossumBot#89]
When testing the bot on a discord server, every command but the !arturedebil command works, and I do have the update code for it. When I tried the old code for the command it again didn't work but this time I got a message on the console with an error. I am not too experienced with code and any help would be appreciated.

**Comment by Barsik008** [comment]
@Swampyemerson are intents enabled?

**Comment by lamo-git** [comment]
@Barsik008 i am having the same issue and my intents are enabled

**Comment by Barsik008** [comment]
@lamo-git does the bot have admin perms?

**Comment by lamo-git** [comment]
@Barsik008 yes, just the admin permission though, should i enable every other permission including admin? or does the bot need the admin role in the server?

**Comment by Barsik008** [comment]
@lamo-git The bot only needs the admin permission, can you send me a screenshot of the server roles?

**Comment by lamo-git** [comment]
![image](https://user-images.githubusercontent.com/66180365/107542285-077f9400-6b96-11eb-8650-5aa97a97128b.png)
![image](https://user-images.githubusercontent.com/66180365/107542305-0cdcde80-6b96-11eb-9de0-b80908878ab9.png)
tic tac toe bot is the name of the possumbot

**Comment by Barsik008** [comment]
@lamo-git try moving the role higher.

**Comment by lamo-git** [comment]
@Barsik008 ah ok, it seems that it can only ban people in the server with roles below the bot itself
