### ISSUE TITLE
Hey! 

### ISSUE THREAD

**Issue by CherriVirus** [Barsik008/PossumBot#9]
Hey, I was wondering what it meant by console like what console is it talking about? Is it the node.js? Console like what console sorry for me being a moronic cow but can you show a picture of what console it is!

Love Cherri

**Comment by Barsik008** [comment]
Windows console click win+r and type in cmd and click enter it should bring up a console.
![image](https://user-images.githubusercontent.com/8159670/71545475-f901f900-2950-11ea-8ffe-828ce23901ad.png)
