### ISSUE TITLE
Don't know where to enter the commands

### ISSUE THREAD

**Issue by amoney232423** [Barsik008/PossumBot#90]
I got everything set up with the bot. Loading Commands...
PossumBot Is Now Activated ----Says this. 

However, I don't know where to enter the commands. It won't let me type anything in cmd after activating the bot>

**Comment by amoney232423** [comment]
@Barsik008

**Comment by Barsik008** [comment]
In the discord server...

**Comment by amoney232423** [comment]
Is something else suppose to open because it says 'WScript.Sleep' is not recognized as an internal or external command,
C:\Users\Rocke\Desktop\PossumBot-master>node bot.js
Loading Commands...
PossumBot Is Now Activated

**Comment by Barsik008** [comment]
@amoney232423 launch the bot through the console
