### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by amoney232423** [Barsik008/PossumBot#91]
'WScript.Sleep' is not recognized as an internal or external command,
operable program or batch file. 
I'm getting this error message when running the bat

**Comment by amoney232423** [comment]
Please help. :(

**Comment by amoney232423** [comment]
I followed all the steps and the bot is activated.

**Comment by amoney232423** [comment]
![image](https://user-images.githubusercontent.com/78401233/106680715-48671f80-657c-11eb-959f-479abef91417.png)

**Comment by Barsik008** [comment]
@amoney232423 try starting the bot through the console.

**Comment by xeRRR** [comment]
@amoney232423 If it didn't work, go to where your files are, cd (file path), there's a tut online, then type exactly this (cmd admin):
npm install discord.js 
And hit enter.
After you installed it, type this:
node bot.js
Then hit enter. Hope it worked :-)
