### ISSUE TITLE
commands break

### ISSUE THREAD

**Issue by potatoplayzzz** [Barsik008/PossumBot#94]
All the commands work fine, but when I do !arturdebil, it just bans one person then it breaks, none of the other commands work.

**Comment by potatoplayzzz** [comment]
I tested it on a server with 2 people

**Comment by Barsik008** [comment]
@potatoplayzzz are intents enabled?

**Comment by potatoplayzzz** [comment]
yea I followed all your instructions

**Comment by Dogleader6** [comment]
I think the problem is that one person is the owner, so they can't be banned
